#!/bin/bash
#SBATCH -t 24:00:00
#SBATCH -p defq
#SBATCH -N 1
#SBATCH --ntasks-per-node 1
#SBATCH --mail-type ALL
#SBATCH -C EGRESS

# echo commands to stdout
set -x 

# Species
Species = \'Lucidota_sp\'

# First number
a=1

# Second number
b=1

# Set path 
WD=/home/waldrop@chapman.edu/firefly
MatWD=\'$WD\'

# move to working directory
cd "${WD}"/src/matlab

# add appropriate modules
module load matlab

# run matlab program
matlab -r "entsniff(${WD},${Species},$a:$b,1);exit"

wait
